# .gitlab-ci.yml
image: node:20  # Use an appropriate Node.js version

stages:
  - build
  - release

build:
  stage: build
  script:
    - cd Backend  # Change to the Backend directory
    - npm install  # Install dependencies
    - npm run make  # Compile the Electron app
  artifacts:
    paths:
      - Backend/out/  # Adjust this path if your build output directory is different
  only:
    - master  # or your target branch, e.g., 'main'

release:
  stage: release
  script:
    - echo "Creating release for version $CI_COMMIT_TAG..."
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
        --data "name=Release $CI_COMMIT_TAG" \
        --data "tag_name=$CI_COMMIT_TAG" \
        --data "description=Release notes for version $CI_COMMIT_TAG" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - tags
